# Generated by Django 2.2.15 on 2023-02-13 12:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=50)),
                ('mensagem', ckeditor.fields.RichTextField()),
                ('data_cria', models.DateTimeField(auto_now=True)),
                ('data_visu', models.DateTimeField()),
                ('data_resp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Perguntas',
            },
        ),
    ]
