# Generated by Django 2.2.15 on 2023-02-13 13:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0034_adsbottombanner_website'),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=50)),
                ('mensagem', ckeditor.fields.RichTextField()),
                ('data_cria', models.DateTimeField(auto_now=True)),
                ('data_visu', models.DateTimeField(blank=True)),
                ('data_resp', models.DateTimeField(blank=True)),
                ('ads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Ads')),
            ],
            options={
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
    ]
