# Generated by Django 2.2.15 on 2023-04-20 14:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_auto_20230213_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='data_resp',
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resp', models.DateTimeField(auto_now=True)),
                ('mensagem', ckeditor.fields.RichTextField(help_text='O texto não pode conter endereços de email ou números de telefone')),
                ('nome', models.CharField(max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Question')),
            ],
            options={
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
