# Generated by Django 2.2.15 on 2023-04-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_auto_20230420_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='mensagem',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='nome',
            new_name='name',
        ),
    ]
