# Generated by Django 2.2.15 on 2023-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_auto_20230420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_visu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
