# Generated by Django 2.2.15 on 2023-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_auto_20230421_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='data_cria',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criação'),
        ),
    ]
