# Generated by Django 2.2.15 on 2023-08-14 13:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_auto_20230421_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rel_message',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='Nova', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='message',
            field=ckeditor.fields.RichTextField(help_text='O texto não pode conter endereços de email ou números de telefone'),
        ),
    ]
