# Generated by Django 2.2.15 on 2023-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0008_auto_20230814_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='email',
            new_name='from_email',
        ),
        migrations.AddField(
            model_name='question',
            name='to_email',
            field=models.EmailField(default='fmortara+default@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
