# Generated by Django 3.2.10 on 2023-09-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0009_auto_20230817_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(default='Nova', max_length=10),
        ),
    ]
