# Generated by Django 2.2.15 on 2022-10-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0030_remove_ads_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name_plural': 'Classificados'},
        ),
        migrations.AlterModelOptions(
            name='adsimages',
            options={'verbose_name_plural': 'Imagens de classificados'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterField(
            model_name='ads',
            name='condition',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Usado - semi-novo', 'Usado - semi-novo'), ('Usado - bom estado', 'Usado - bom estado'), ('Usado - requer reapros', 'Usado - requer reparo'), ('Sucata', 'Sucata')], max_length=100),
        ),
        migrations.AlterField(
            model_name='adsbottombanner',
            name='title',
            field=models.CharField(blank=True, default='Inclua seu anúncio', max_length=200),
        ),
        migrations.AlterField(
            model_name='adsrightbanner',
            name='title',
            field=models.CharField(blank=True, default='Inclua seu anúncio', max_length=200),
        ),
        migrations.AlterField(
            model_name='adstopbanner',
            name='title',
            field=models.CharField(blank=True, default='Inclua seu anúncio', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=50),
        ),
    ]
