# Generated by Django 2.2.15 on 2022-11-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_auto_20221027_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_abbrev',
            field=models.CharField(default='dd', max_length=2),
            preserve_default=False,
        ),
    ]
