# Generated by Django 2.2.15 on 2022-11-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0032_state_state_abbrev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='state_abbrev',
        ),
    ]
