# Generated by Django 2.2.15 on 2023-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0033_remove_state_state_abbrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbottombanner',
            name='website',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
    ]
