# Generated by Django 3.2.10 on 2023-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0034_adsbottombanner_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsrightbanner',
            name='website',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adstopbanner',
            name='website',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
