# Generated by Django 3.2.10 on 2023-10-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0035_auto_20230919_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='pub_status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Pendente Publicar', 'Pendente Publicar'), ('Publicado', 'Publicado'), ('Oculto Usuario', 'Oculto Usuario'), ('Retirado Admin', 'Retirado Admin')], default='Novo', max_length=20),
        ),
    ]
